//any function can throw an error
function functionWithException() {
  throw new Error("test exception");
}
